### PR TITLE
Add species search functionality

### PR DESCRIPTION
**Pull request by Rashmil-1999**
This PR adds the Species list page and search functionality. Currently, the search field only searches across a fixed set of column names that are set on the API side and the user cannot select which columns to search from. This is something I wanted to get some clarification on regarding the addition of checkboxes that dynamically create the search query. For that, I changed the API Endpoint to GET from POST.

To go to the Species page enter "#/species". I have paginated all the listed species and upon clicking the species, you can see the details of the species. The details page requires a lot of formatting as we now have to show more information.

### CODE REVIEW

**Review by ka7eh — CHANGES_REQUESTED** [review]
Looking good. I added a few comments. Can you also run `npm run lint` and fix the issues there?

**Comment by ka7eh** [comment]
Can you also resolve the conflicts with `develop`?

**Comment by Rashmil-1999** [comment]
> Can you also resolve the conflicts with `develop`?

The reason why I was a bit hesitant in resolving the conflicts is that it is asking me to modify the package-lock file too and that is auto-generated. For some reason, if I do pull and then push, still it is not able to resolve any issues. I can just keep all incoming (my changes) and discard the existing changes if that is okay.

**Comment by Rashmil-1999** [comment]
> Looking good. I added a few comments. Can you also run `npm run lint` and fix the issues there?

Yes, I forgot to run that command. I just did. Will update the PR soon.

**Comment by ka7eh** [comment]
> > Can you also resolve the conflicts with `develop`?
> 
> The reason why I was a bit hesitant in resolving the conflicts is that it is asking me to modify the package-lock file too and that is auto-generated. For some reason, if I do pull and then push, still it is not able to resolve any issues. I can just keep all incoming (my changes) and discard the existing changes if that is okay.

That's fine. Just keep the latest lock and discard the other.

**Review by ka7eh — APPROVED** [review]

**Pull request merged**
